# Generated by Django 3.2 on 2021-04-09 21:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_review2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review2',
            new_name='p2R2',
        ),
    ]
