# Generated by Django 3.2 on 2021-04-09 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_review2_p2r2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='p2r2',
            old_name='content',
            new_name='content2',
        ),
        migrations.RenameField(
            model_name='p2r2',
            old_name='product',
            new_name='product2',
        ),
        migrations.RenameField(
            model_name='p2r2',
            old_name='user',
            new_name='user2',
        ),
    ]
