# Generated by Django 3.2 on 2021-04-09 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_display'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='p2r2',
            name='product2',
        ),
        migrations.RemoveField(
            model_name='p2r2',
            name='user2',
        ),
        migrations.DeleteModel(
            name='display',
        ),
        migrations.DeleteModel(
            name='p2R2',
        ),
    ]
