# Generated by Django 3.2 on 2021-04-11 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210410_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.complited'),
        ),
        migrations.AlterField(
            model_name='complited',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
